version: '3'
networks:
  gb-network:
    driver: bridge

services:
  back-end:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    networks:
      - gb-network

  front-end:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    networks:
      - gb-network
    depends_on:
      - back-end